// ═══════════════════════════════════════════════════════════════════════════════
// AGENT TYPES — Agent Definitions, Tools, and Knowledge
// Canonical source of truth for all Agent domain types.
// Column-level alignment: every scalar field on `Agent` mirrors a column in
// the `agents` Drizzle table (src/lib/db/schema.ts). Expanded relations
// (`tools`, `knowledge`) are optional hydration fields NOT present in the DB row.
// ═══════════════════════════════════════════════════════════════════════════════

import type { UseCaseType } from "./genesis";
import type { MCPTool, KnowledgeDoc } from "./tool";

// ─── Enums ───────────────────────────────────────────────────────────────────

/**
 * Agent operational status.
 * Stored in: agents.status
 */
export type AgentStatus = "active" | "paused" | "error" | "archived";

// ─── Core Entities ───────────────────────────────────────────────────────────

/**
 * Core Agent entity.
 * Represents an AI persona with configuration and capabilities.
 *
 * Every scalar property maps 1:1 to a column on the `agents` SQLite table.
 * The `tools` and `knowledge` fields are populated only when the query
 * includes a Drizzle `with:` clause or a manual join.
 */
export interface Agent {
  /** PK — auto-generated UUID */
  id: string;

  /** FK → user_profiles.id */
  ownerId: string;

  /** Display name */
  name: string;

  /** Avatar — URL, emoji, or data URI */
  avatar: string | null;

  /** Short description of the agent's purpose */
  description: string | null;

  // ── Persona Configuration ──────────────────────────────────────────────

  /** System prompt that defines personality and behavior */
  systemPrompt: string;

  /** Creativity/randomness (0.0 – 2.0, default 0.7) */
  temperature: number;

  /** Preferred LLM identifier (e.g. "ollama/llama3.1", "gpt-4o") */
  modelPreference: string;

  /** Voice ID for TTS (optional, future use) */
  voiceId: string | null;

  // ── State ──────────────────────────────────────────────────────────────

  /** Current operational status */
  status: AgentStatus;

  // ── Genesis / Template Tracking ────────────────────────────────────────

  /** Whether this agent definition is a reusable template */
  isTemplate: boolean;

  /** Use case tag linking back to the Genesis flow */
  genesisTag: UseCaseType | null;

  /** If this agent was spawned from a template, the template's ID */
  templateId: string | null;

  // ── Metadata / Counters ────────────────────────────────────────────────

  /** Total chat sessions involving this agent */
  totalConversations: number;

  /** Total messages generated by this agent */
  totalMessages: number;

  /** Timestamp of last activity */
  lastActiveAt: Date | null;

  // ── Timestamps ─────────────────────────────────────────────────────────

  createdAt: Date;
  updatedAt: Date;

  // ── Expanded Relations (NOT in DB row) ─────────────────────────────────

  /** MCP tool assignments (via agent_tools join table) */
  tools?: AgentTool[];

  /** Knowledge document assignments (via agent_knowledge join table) */
  knowledge?: AgentKnowledge[];
}

/**
 * Agent-Tool assignment (join table row).
 * Links an agent to an MCP tool with optional per-agent configuration.
 * Maps to: agent_tools table.
 */
export interface AgentTool {
  id: string;

  /** FK → agents.id */
  agentId: string;

  /** FK → mcp_tools.id */
  toolId: string;

  /** Per-agent tool configuration overrides (JSON) */
  config: Record<string, unknown>;

  /** Whether this tool binding is active */
  isEnabled: boolean;

  createdAt: Date;

  /** Expanded relation — populated when queried with `with: { tool: true }` */
  tool?: MCPTool;
}

/**
 * Agent-Knowledge assignment (join table row).
 * Links an agent to a knowledge document for RAG retrieval scoping.
 * Maps to: agent_knowledge table.
 */
export interface AgentKnowledge {
  id: string;

  /** FK → agents.id */
  agentId: string;

  /** FK → knowledge_docs.id */
  docId: string;

  /** Relevance score for ranking (optional, set by indexing pipeline) */
  relevanceScore: number | null;

  /** Custom metadata for this specific link (JSON) */
  customMetadata: Record<string, unknown>;

  createdAt: Date;

  /** Expanded relation — populated when queried with `with: { document: true }` */
  document?: KnowledgeDoc;
}

// ─── API Payloads ────────────────────────────────────────────────────────────

/**
 * Agent creation payload.
 * POST /api/agents
 */
export interface CreateAgentPayload {
  name: string;
  avatar?: string;
  description?: string;
  systemPrompt: string;
  temperature?: number;
  modelPreference?: string;
  voiceId?: string;
  toolIds?: string[];
  knowledgeDocIds?: string[];
}

/**
 * Agent update payload (partial).
 * PATCH /api/agents/[agentId]
 */
export type UpdateAgentPayload = Partial<
  Omit<CreateAgentPayload, "toolIds" | "knowledgeDocIds">
> & {
  toolIds?: string[];
  knowledgeDocIds?: string[];
};

// ─── UI / Display Types ──────────────────────────────────────────────────────

/**
 * Agent with computed/expanded fields for UI display.
 * Returned by GET /api/agents/[agentId] with full hydration.
 */
export interface AgentWithDetails extends Agent {
  enabledTools: MCPTool[];
  knowledgeDocs: KnowledgeDoc[];
  recentSessions: {
    id: string;
    title: string | null;
    lastMessageAt: Date | null;
    messageCount: number;
  }[];
}

// ─── Execution Types ─────────────────────────────────────────────────────────

/**
 * Agent execution context.
 * Passed to the AI Gateway (UnifiedGateway) when running an agent.
 */
export interface AgentExecutionContext {
  agent: Agent;
  sessionId: string;
  messageHistory: {
    role: "user" | "assistant" | "system" | "tool";
    content: string;
    metadata?: Record<string, unknown>;
  }[];
  availableTools: MCPTool[];
  knowledgeContext?: string;
}

/**
 * Agent execution result.
 * Returned by the gateway after a complete (non-streaming) invocation.
 */
export interface AgentExecutionResult {
  content: string;
  toolCalls?: {
    toolName: string;
    arguments: Record<string, unknown>;
    result?: unknown;
    error?: string;
  }[];
  tokensUsed?: {
    prompt: number;
    completion: number;
    total: number;
  };
  modelUsed: string;
  provider: string;
  executionTimeMs: number;
}

// ─── Filter / List Types ─────────────────────────────────────────────────────

/**
 * Agent filter options for listing.
 * Used by the agentStore Zustand store and GET /api/agents query params.
 */
export interface AgentFilterOptions {
  status?: AgentStatus;
  genesisTag?: UseCaseType;
  isTemplate?: boolean;
  searchQuery?: string;
  sortBy: "name" | "createdAt" | "lastActiveAt" | "totalMessages";
  sortOrder: "asc" | "desc";
}

/**
 * Agent list response.
 * GET /api/agents → response
 */
export interface AgentListResponse {
  agents: Agent[];
  totalCount: number;
  hasMore: boolean;
  nextCursor?: string;
}
